package edu.whut.bear.panda.service;

import org.springframework.stereotype.Service;

/**
 * @author Spring-_-Bear
 * @datetime 2022/5/8 23:31
 */
@Service
public interface TransferService {
    /**
     * Get the file upload token generated by Qiniu server
     *
     * @param key      File key named by Qiniu
     * @param fileType The type of the file uploaded
     * @return String[0]:domain     String[1]:bucket     String[2]:uploadToken
     */
    String[] getFileUploadToken(String key, Integer fileType);

    /**
     * Get file download url generated by Qiniu server
     *
     * @param key File key named by Qiniu
     * @return Private file download url
     */
    String getBookDownloadUrl(String key);
}